# Generated by Django 3.1.7 on 2021-05-02 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20210502_1905'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='useraccount',
            table='useraccount',
        ),
    ]
