# Generated by Django 3.1.7 on 2021-05-02 16:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 5, 2, 16, 28, 23, 311065, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 16, 28, 23, 311065, tzinfo=utc)),
        ),
    ]
