# Generated by Django 3.1.7 on 2021-05-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20210503_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='address',
            field=models.CharField(default='n/a', max_length=100),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='city',
            field=models.CharField(default='n/a', max_length=25),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='mobile',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='postal',
            field=models.CharField(default='n/a', max_length=20),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='street',
            field=models.CharField(default='n/a', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
