# Generated by Django 3.1.7 on 2021-05-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20210512_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccine',
            name='info',
        ),
        migrations.AddField(
            model_name='vaccine',
            name='company',
            field=models.CharField(default='n/a', max_length=200),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='country',
            field=models.CharField(default='n/a', max_length=200),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='disease',
            field=models.CharField(default='n/a', max_length=200),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='vactype',
            field=models.CharField(choices=[('1', 'Government Vaccine'), ('2', 'Non-Government Vaccine')], default='1', max_length=25),
        ),
    ]
