# Generated by Django 3.1.7 on 2021-05-14 15:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20210512_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduleappoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic', models.CharField(choices=[('DCH', 'Dhaka Community Hospital'), ('JEWMCH', 'Japan East West Medical College Hospital, Dhaka'), ('EHD', 'Evercare Hospital, Dhaka')], max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 5, 14, 15, 47, 8, 544129, tzinfo=utc))),
                ('city', models.CharField(choices=[('Dhaka', 'Dhaka (ঢাকা)'), ('Barishal', 'Barishal (বরিশাল )'), ('Chittagong', 'Chittagong (চট্টগ্রাম)'), ('Mymensingh', 'Mymensingh (ময়মনসিংহ)'), ('Khulna', 'Khulna (খুলনা )'), ('Rajshahi', 'Rajshahi (রাজশাহী)'), ('Rangpur', 'Rangpur (রংপুর )'), ('Sylhet', 'Sylhet (সিলেট )')], max_length=100)),
            ],
            options={
                'db_table': 'scheduleappoint',
            },
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
