# Generated by Django 3.1.7 on 2021-05-15 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20210514_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleappoint',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
