# Generated by Django 3.1.7 on 2021-05-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20210515_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleappoint',
            name='time',
            field=models.CharField(choices=[('1', 'Morning'), ('2', 'Evening')], default='n/a', max_length=100),
        ),
    ]
