# Generated by Django 3.1.7 on 2021-05-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_vaccinetrack'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaccinetrack',
            options={'ordering': ['vaccine_name']},
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='age',
            field=models.IntegerField(),
        ),
    ]
