# Generated by Django 3.1.7 on 2021-05-23 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_auto_20210522_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinetrack',
            name='username',
            field=models.ForeignKey(db_column='first_name', on_delete=django.db.models.deletion.CASCADE, to='pages.useraccount'),
        ),
        migrations.AlterField(
            model_name='vaccinetrack',
            name='vaccine_name',
            field=models.ForeignKey(db_column='vacName', on_delete=django.db.models.deletion.CASCADE, to='pages.vaccine'),
        ),
    ]
