# Generated by Django 3.2.5 on 2021-07-24 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_auto_20210523_1407'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scheduleappoint',
        ),
        migrations.RemoveField(
            model_name='vaccinetrack',
            name='username',
        ),
        migrations.RemoveField(
            model_name='vaccinetrack',
            name='vaccine_name',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='age',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='street',
        ),
        migrations.DeleteModel(
            name='Vaccine',
        ),
        migrations.DeleteModel(
            name='VaccineTrack',
        ),
    ]
